CREATE TABLE CREW(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL UNIQUE,
    MASTER VARCHAR2(20) NOT NULL,
    IMAGE_FILE VARCHAR2(100) NULL,
    DESCRIBE VARCHAR2(2000) NULL,
    MEMBER NUMBER DEFAULT 1
);

CREATE TABLE MEETING(
    ID NUMBER PRIMARY KEY,
    MASTER VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    LOCATION VARCHAR2(50) NOT NULL,
    MEETING_DATE DATE NOT NULL,
    LONGITUDE VARCHAR2(50) NULL,
    LATITUDE VARCHAR2(50) NULL,
    TOTAL_MEMBER NUMBER DEFAULT 2,
    JOINED_MEMBER NUMBER DEFAULT 1
);
CREATE TABLE MEETING_JOIN(
    MEETING_ID NUMBER,
    MEMBER_ID VARCHAR2(100),
    CONSTRAINT MEETING_JOIN_PK PRIMARY KEY(MEETING_ID,MEMBER_ID),
    CONSTRAINT MEETING_ID_FK FOREIGN KEY(MEETING_ID) REFERENCES MEETING(ID)ON DELETE CASCADE,
    CONSTRAINT USER_ID_FK FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID)ON DELETE CASCADE
);

CREATE TABLE MEMBER(
    NAME VARCHAR2(50) NOT NULL,
    ID VARCHAR2(100) PRIMARY KEY,
    PASSWORD VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    TOTAL_DISTANCE BINARY_FLOAT DEFAULT 0,
    TOTAL_DURATION BINARY_FLOAT DEFAULT 0,
    PROFILE_IMAGE VARCHAR2(100) NULL,
    INTRODUCE VARCHAR2(1000) NULL,
    NICKNAME VARCHAR2 (100) NOT NULL, 
    POSTCODE VARCHAR2(100) NOT NULL,
    ADDRESS_ROAD VARCHAR2(1000) NOT NULL,
    ADDRESS_DETAIL VARCHAR2(1000) 
);


CREATE TABLE CREW_JOIN(
    CREW_ID NUMBER ,
    MEMBER_ID VARCHAR2(100),
    CONSTRAINT CREW_JOIN_PK PRIMARY KEY(CREW_ID,MEMBER_ID),
    CONSTRAINT CREW_ID_FK2 FOREIGN KEY(CREW_ID) REFERENCES CREW(ID)ON DELETE CASCADE,
    CONSTRAINT USER_ID_FK2 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID)ON DELETE CASCADE
);



CREATE TABLE BOARD(
    ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(2000),
    WRITER VARCHAR2(20) NOT NULL, 
    IMAGE_FILE VARCHAR2(100),
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOARD_ID NUMBER NOT NULL,
    CONSTRAINT FK_BOARD_ID FOREIGN KEY(BOARD_ID) REFERENCES CREW(ID) ON DELETE CASCADE
    
);

CREATE TABLE JOURNEY(
    ID NUMBER NOT NULL PRIMARY KEY,
    MEMBER_ID VARCHAR2(100),
    DURATION VARCHAR2(256) NOT NULL,
    DISTANCE VARCHAR2(256) NOT NULL,
    AVG_SPEED VARCHAR2(256) NOT NULL,
    RUNNING_DATE VARCHAR2(256) NOT NULL,
    CONSTRAINT USER_ID_FK3 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID)ON DELETE CASCADE
);

CREATE TABLE LOCATION (
    ID NUMBER NOT NULL PRIMARY KEY,
    JOURNEY_ID NUMBER NOT NULL,
    LONGITUDE BINARY_FLOAT NOT NULL,
    LATITUDE BINARY_FLOAT NOT NULL,
    CONSTRAINT FK1 FOREIGN KEY (JOURNEY_ID) REFERENCES JOURNEY (ID) ON DELETE CASCADE
);

CREATE TABLE REPLY(
    ID NUMBER PRIMARY KEY,
    BOARD_ID NUMBER NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    PARENT_REPLY NUMBER DEFAULT 0 NOT NULL, 
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT REPLY_BOARD_ID_FK FOREIGN KEY (BOARD_ID) REFERENCES BOARD(ID),
    CONSTRAINT REPLY_WRITER_FK FOREIGN KEY (WRITER) REFERENCES MEMBER(ID)
);