CREATE TABLE CREW(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL UNIQUE,
    MASTER VARCHAR2(20) NOT NULL,
    IMAGE_FILE VARCHAR2(100) NULL,
    DESCRIBE VARCHAR2(2000) NULL,
    MEMBER NUMBER DEFAULT 1
);

CREATE TABLE MEETING(
    ID NUMBER PRIMARY KEY,
    MASTER VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    LOCATION VARCHAR2(50) NOT NULL,
    MEETING_DATE DATE NOT NULL,
    longitude BINARY_FLOAT NULL,
    latitude BINARY_FLOAT NULL,
    MEMBER NUMBER DEFAULT 2,
    JOINEDMEMBER NUMBER DEFAULT 1
);
CREATE TABLE MEETINGJOIN(
    MEETING_ID NUMBER ,
    MEMBER_ID varchar(100),
    CONSTRAINT MEETING_JOIN_PK PRIMARY KEY(MEETING_ID,MEMBER_ID),
    CONSTRAINT MEETING_ID_FK FOREIGN KEY(MEETING_ID) REFERENCES MEETING(ID)ON DELETE CASCADE,
    CONSTRAINT USER_ID_FK FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID)ON DELETE CASCADE
);

CREATE TABLE MEMBER(
    NAME VARCHAR2(50) NOT NULL,
    ID varchar2(100) PRIMARY KEY,
    PASSWORD VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    TOTALDISTANCE BINARY_FLOAT DEFAULT 0,
    TOTALDURATION BINARY_FLOAT DEFAULT 0,
    PROFILE_IMAGE VARCHAR2(100) NULL,
    INTRODUCE VARCHAR2(1000) NULL,
    NICKNAME VARCHAR2 (100) NOT NULL, 
    POSTCODE VARCHAR2(100) NOT NULL,
    ADDRESS_ROAD VARCHAR2(1000) NOT NULL,
    ADDRESS_DETAIL VARCHAR2(1000) 
);

select * from member;

CREATE TABLE CREWJOIN(
    CREW_ID NUMBER ,
    MEMBER_ID varchar2(100),
    CONSTRAINT MEETING_JOIN_PK2 PRIMARY KEY(CREW_ID,MEMBER_ID),
    CONSTRAINT CREW_ID_FK2 FOREIGN KEY(CREW_ID) REFERENCES CREW(ID)ON DELETE CASCADE,
    CONSTRAINT USER_ID_FK2 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID)ON DELETE CASCADE
);



CREATE TABLE BOARD( -- ????? ???, ¡À?????? ???
    ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(2000),
    WRITER VARCHAR2(20) NOT NULL, -- ?¨¨? USER ????? FK ??????
    IMAGE_FILE VARCHAR2(100),
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOARD_ID NUMBER NOT NULL,
    CONSTRAINT FK_BOARD_ID FOREIGN KEY(BOARD_ID) REFERENCES BOARD(ID) ON DELETE CASCADE
    
);

CREATE TABLE journey(
    journeyID Number NOT NULL PRIMARY KEY,
    MEMBER_ID varchar2(100),
    duration varchar2(256) NOT NULL,
    distance varchar2(256) NOT NULL,
    avgspeed VARCHAR2(256) NOT NULL,
    runningdate varchar2(256) NOT NULL,
    CONSTRAINT USER_ID_FK3 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID)ON DELETE CASCADE
);

CREATE TABLE location (
    locationID NUMBER NOT NULL PRIMARY KEY,
    journeyID NUMBER NOT NULL,
    longitude BINARY_FLOAT NOT NULL,
    latitude BINARY_FLOAT NOT NULL,
    CONSTRAINT fk1 FOREIGN KEY (journeyID) REFERENCES journey (journeyID) ON DELETE CASCADE
);



DESC MEMBER;








INSERT INTO BOARD(ID, TITLE, CONTENT, WRITER, BOARD_ID)
VALUES(1, '????????', '????????~ ??? ???????', 'DOORUN', 0);

INSERT INTO BOARD(ID, TITLE, CONTENT, WRITER, BOARD_ID)
VALUES((SELECT NVL(MAX(ID),1) FROM POST)+1, '????????', '????????~ ??? ???????', 'DOORUN', 1);

INSERT INTO BOARD(ID, TITLE, CONTENT, WRITER, BOARD_ID)
VALUES((SELECT NVL(MAX(ID),1) FROM POST)+1, '????????', '????????~ ??? ???????', 'DOORUN', 2);

CREATE TABLE REPLY(
    ID NUMBER PRIMARY KEY,
    WRITER VARCHAR2(20) NOT NULL, -- ?¨¨? USER ????? FK ??????
    CONTENT VARCHAR2(500),
    POST_ID NUMBER NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    PARENT_ID NUMBER DEFAULT 0 NOT NULL, -- 0 ??? ?¥è? ??? ????
    CONSTRAINT FK_POST_ID FOREIGN KEY(POST_ID) REFERENCES POST(ID) ON DELETE CASCADE
);

INSERT INTO REPLY(ID, WRITER, CONTENT, POST_ID)
VALUES((SELECT NVL(MAX(ID),0) FROM REPLY)+1, 'DOORUN', 'EVENT',1);

INSERT INTO REPLY(ID, WRITER, CONTENT, POST_ID)
VALUES((SELECT NVL(MAX(ID),0) FROM REPLY)+1, 'DOORUN', 'FREE',2);

INSERT INTO REPLY(ID, WRITER, CONTENT, POST_ID)
VALUES((SELECT NVL(MAX(ID),0) FROM REPLY)+1, 'DOORUN', 'DOORUN',3);

COMMIT;

CREATE TABLE REPLY(
    ID NUMBER PRIMARY KEY,
    BOARD_ID NUMBER NOT NULL,
    WRITER VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    PARENT_REPLY NUMBER DEFAULT 0 NOT NULL, -- 0: ´ë´ñ±ÛÀÌ ¾Æ´Ô
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT REPLY_BOARD_ID_FK FOREIGN KEY (BOARD_ID) REFERENCES BOARD(ID),
    CONSTRAINT REPLY_WRITER_FK FOREIGN KEY (WRITER) REFERENCES MEMBER(ID)
);